// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyCQK9lg7DLYhWyc2tWXMopMLwFc3O6Zk5U",
      authDomain: "namdhina.firebaseapp.com",
      databaseURL: "https://namdhina-default-rtdb.firebaseio.com",
      projectId: "namdhina",
      storageBucket: "namdhina.appspot.com",
      messagingSenderId: "235960579541",
      appId: "1:235960579541:web:5d7b8ecaed44545a28795c",
      measurementId: "G-K8XF7J14EC");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgGhPCYBtRkENwOssQ4vuRwTG8PvKfl0U',
    appId: '1:235960579541:ios:33dc9da108f17b3928795c',
    messagingSenderId: '702136924579',
    projectId: 'namdhina',
    storageBucket: 'namdhina.appspot.com',
    iosClientId:
        '235960579541-kh1o9qqhml2dq9vid2g276a4oqv322hs.apps.googleusercontent.com',
    iosBundleId: 'com.namdhina.news',
  );
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCQK9lg7DLYhWyc2tWXMopMLwFc3O6Zk5U",
      authDomain: "namdhina.firebaseapp.com",
      databaseURL: "https://namdhina-default-rtdb.firebaseio.com",
      projectId: "namdhina",
      storageBucket: "namdhina.appspot.com",
      messagingSenderId: "235960579541",
      appId: "1:235960579541:web:5d7b8ecaed44545a28795c",
      measurementId: "G-K8XF7J14EC");
}
